name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # updates every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: no
          plugin_contributors: yes
          plugin_contributors_sections: repos,prs
          plugin_contributors_contributions: yes
          plugin_contributors_contributions_limit: 200
          committer_message: "chore: update PR leaderboard"
